### ISSUE TITLE
Complete the approval-workflow e2e harness (currently excluded)

### ISSUE THREAD

**Issue by iamnaii** [iamnaii/BESTCHOICE#1192]
`apps/api/e2e/approval-workflow.e2e-spec.ts` was written **ahead** of its dependency PRs (#912/#923/#930/#931/#932/#933). Its harness was never finished:
- helper services are provided via **string tokens** (`{ provide: 'StatusTransitionService', ... }`) instead of the real class tokens, so the service's injected deps resolve to `{}` via `.useMocker(() => ({}))` → `this.transition.assertCanApprove is not a function`.
- it lacks `approval_enabled = 'true'` in the systemConfig mock (submit-for-approval is now gated on it).
- it calls `approve(id, userId)` without the `userRole` 3rd arg, so the OWNER root-of-trust bypass (D1.2.1.3 approvers-list gate) never fires.

The spec "passed by failing/early-returning" until the unit-test fix in #1191 unmasked it. To unblock the merge gate it is **temporarily excluded** via `testPathIgnorePatterns` in `apps/api/e2e/jest-e2e.json` (PR #1191) — matching the file's own original "excluded until the dependency stack lands" intent.

### To re-enable
1. Provide `StatusTransitionService`, `DocNumberService`, `LineAggregatorService`, `JePreviewService` (+ any other approval-path deps) as **class-token** mocks.
2. Add `approval_enabled → 'true'` to the systemConfig mock.
3. Pass `'OWNER'` as the 3rd arg to `approve(id, userId, role)` in the transition + DRAFT tests (keep the non-approver test as-is).
4. Fix the submit-for-approval audit-log assertion.
5. Remove the entry from `testPathIgnorePatterns`.

This is a stale **test harness**, not a production bug — the approval flow works in prod.
